### ISSUE TITLE
9.5 preview: issues and wishes

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#165]
ISSUES
1. Rescan midi device: force-close returned :(
2. Past selected settings: doesn't work. 
![past-selected](https://cloud.githubusercontent.com/assets/16202038/12745059/7e173f24-c965-11e5-9f92-daf9e6a6b5b3.png)
3. Probably I missed something, but the problem is:
when I pick the tool like brush or gradient, the assigned profile is loaded. But, when I drop the tool, the default profile associated with the DEVELOP module aren't loaded back. I can only return it via choosing the LIBRARY, then DEVELOP. It's annoying... 
4. I'm not sure for this version because past settings is broken, but in the previouse version lens profile was ignored.

WISHES
Past setting dialog windows.
Thank you for the group button.
But can you please add some VISUAL separators in to the list? It's very difficult to find the single option to check-uncheck in the LOOOONG list. Also, some grouping is not logical, I believe.
![groups](https://cloud.githubusercontent.com/assets/16202038/12745458/5680c348-c967-11e5-98ed-a8fc0ed246a9.jpg)

Also, you mentioned that values and parameters changes should displayed. I checked up both checkboxes relative to this idea in the OPTIONS but I see only profile changes announces.

**Comment by rsjaffe** [comment]
Argh. I fixed the selective paste issue. Some old code crept into the release version and I removed it. The current version in the release now has the correct code.

Rescan works fine on my machine, as does the display of parameter changes. The parameter changes checkbox is on the "Other..." tab of the dialog box--"Show status and activity"--please confirm that it is checked, then we'll have to debug it some more.

As to the profiles change, yes, try adding the develop profile to the develop Loupe view.

**Comment by krakozavr** [comment]
is the corrected version is available for download? :)
Yes, this checkbox is checked, I can confirm :)
Only info about profile's changes still appeared (the white text in on the black background over the screen). No other info I can see.

Profile change.
I added the default profile to LOUPE.
Now, it's interesting :)
Now, I have two notifications about profile's change. The new one over the screen, and the old pop-up notification next to the system tray at the right bottom corner, next to the watches.
When I pick the tool, associated profile is loaded and I receive two confirmation about it, both the new one and the old one. 
When I drop the tool, i receive the new one confirmation only (which say "profile is changing to") but I don't receive the old-style pop-up confirmation, and nothing happened.

Looks like the old confirmation is onle one real, and the new one is based not on the real event but on the expected behavior :)

**Comment by krakozavr** [comment]
redownloaded 9.5, same problems here :( include the setting's copy/past
