### ISSUE TITLE
Shortcut keys in OS X

### ISSUE THREAD

**Issue by tryba2000** [rsjaffe/MIDI2LR#232]
I can not run the function "paste from the previous". I program the cc: 90 KPPasteFromPrevious but nothing happens when I press the button. The "reset all" button works ok.

•Operating system Windows 10
•MIDI2LR version: 0.9.10
•Lightroom version: 6.0
•Lightroom language: PL
•Keyboard language: PL
•MIDI controller: Behringer BCF2000
•Plugin installation directory: E:\Programy\programy foto\MIDI2LR
•Profiles save directory: E:\Programy\programy foto\MIDI2LR\AlexArtPhoto_BehringerBCF2000_MIDI2LR

**Comment by rsjaffe** [comment]
Try the latest hotfix: https://github.com/rsjaffe/MIDI2LR/releases/tag/%60v0.9.10.1 This should fix that issue. (I hope).

**Comment by bozwellox** [comment]
This still isn't working for me on the X-Touch Mini, unless I'm doing something stupid. I've tried using the KPPasteFromPrevious and also assigning the Cmd+Option+v shortcut using the new key mapping options (thanks for those), but I just get an audible OSX "nope" type of sound, and nothing happens.

Has anyone else got this working in the latest version? OSX 10.11.3, LR CC, UK language LR & keyboard.

**Comment by rsjaffe** [comment]
No. Do any of the shortcuts work for you? I've never received any confirmation from Mac users that they work, and so that code is considered "experimental" for Macs. Also, is Lightroom the active application? Unlike with the PC, the key messages won't go to Lightroom unless it is the foreground application.

**Comment by bozwellox** [comment]
@rsjaffe  I'll give it a proper test and get back to you. Just in the middle of a mega edit.

**Comment by emkorec** [comment]
I've tested the shortcuts on my Mac. Result is that only Cmd key does not work for me. That sucks because most of the key-combinations in lightroom includes Cmd.
However Alt/Opt key works well, Shift works well, letters work well. Eg. (Before-after toggle) Alt/Opt+Y works just like Shift+Y. Keystore R for Crop tool works too. But any other keycombination with Cmd or Cmd+Opt, or Cmd+Shift or Cmd+Opt+Shift does not work. Eg Copy/Paste, Paste from Previous and so on.
- MIDI2LR 1.0.0
- OSX El Capitan latest
- English lang op-system and english Lightroom
- Hungarian keyboard

**Comment by rsjaffe** [comment]
That's very odd. I'll check the code.

**Comment by rsjaffe** [comment]
Very odd. The following is a piece of the code used for OS X. The keys set by the user are: 'key' (the key to press), 'Control' (the command key), 'Alt' (the options key) and 'Shift'. Does anyone see an issue here?

```cpp
        const std::wstring utf16str{ utf8_to_utf16(key) };
        const UniChar keychar = utf16str[0];
        d = CGEventCreateKeyboardEvent(source, 0, true);
        u = CGEventCreateKeyboardEvent(source, 0, false);
        CGEventKeyboardSetUnicodeString(d, 1, &keychar);
        CGEventKeyboardSetUnicodeString(u, 1, &keychar);
        flags = CGEventGetFlags(d); //in case KeyCode has associated flag
        if (Control) flags |= kCGEventFlagMaskCommand;
        if (Alt) flags |= kCGEventFlagMaskAlternate;
        if (Shift) flags |= kCGEventFlagMaskShift;
        if (flags != UINT64_C(0))
        {
            CGEventSetFlags(d, static_cast<CGEventFlags>(flags));
            CGEventSetFlags(u, static_cast<CGEventFlags>(flags));
        }
```

**Comment by emkorec** [comment]
Beware that Control is not the same as Command. Mac keyboard has both Ctrl and Cmd keys, but Ctrl is rarely used. All commands made with Ctrl on Windows are made with Cmd (command or apple key) on Mac. Ctrl (control) key does some totally different thing that Windows does not even have a key for (and once again it is rarely used on Macs).

**Comment by emkorec** [comment]
Here you can see: http://media.lifehacker.foxtrot.future.net.uk/wp-content/uploads/sites/55/2014/05/mac-keyboard.jpg
Ctrl = Control (used rarely)
Alt = Option
Cmd = Command or on older Macs it was the "Apple" key
If windows version is ctrl+C than the mac version is Cmd+C.

**Comment by rsjaffe** [comment]
Yes--I use the variable Control for Control in windows, Command in OS X, and mapped it tok CGEventFlagMaskCommand . [The whole set is](https://developer.apple.com/library/mac/documentation/Carbon/Reference/QuartzEventServicesRef/#//apple_ref/c/tdef/CGEventFlags)

```
enum _CGEventFlags {
   kCGEventFlagMaskAlphaShift =    NX_ALPHASHIFTMASK,
   kCGEventFlagMaskShift =         NX_SHIFTMASK,
   kCGEventFlagMaskControl =       NX_CONTROLMASK,
   kCGEventFlagMaskAlternate =     NX_ALTERNATEMASK,
   kCGEventFlagMaskCommand =       NX_COMMANDMASK,
   kCGEventFlagMaskHelp =          NX_HELPMASK,
   kCGEventFlagMaskSecondaryFn =   NX_SECONDARYFNMASK,
   kCGEventFlagMaskNumericPad =    NX_NUMERICPADMASK,
   kCGEventFlagMaskNonCoalesced =  NX_NONCOALSESCEDMASK 
};
typedef uint64_t CGEventFlags;
```

One thing I might try is to send the modifier keys in sequence--currently the modifiers and character key are sent as a single event, which might confuse LR.

**Comment by bozwellox** [comment]
Just tried using the version posted directly above - paste previous isn't working still (set to Command + Option + v in the plugin settings).

**Comment by emkorec** [comment]
Sorry I am not at home at the moment. You should try something else with command key maybe?

**Comment by bozwellox** [comment]
OK so I've done some further testing and it does indeed seem like it is the command key that isn't playing nicely. The following things don't work for me:

Copy (Shift + CMD + C)
Paste (Shift + CMD+ V)
Paste previous (Option + CMD + V)
Targeted adjustments for Hue, Saturation, Luminance, Tone Curve & B&W Mix (all involving the Alt + Shift + CMD keys)

The following things work perfectly and none of them use the CMD key:

Lights out (Shift + L)
Hide panels (Shift + TAB)

It definitely seems like the CMD key is causing the problems for Mac users. Hope this helps - let me know if I can be of any assistance with debugging and wotnot.

**Comment by rsjaffe** [comment]
I'm traveling now, can't do any compiling. I've revised SendKeys.cpp again. I had it sequentially pressing any applicable modifier keys, now just the command key. If you are able to compile for OS X, could you run it and test based on the current develop branch? Thanks. Otherwise, this will have to wait a week.

**Comment by bozwellox** [comment]
I'd happily do that, if I had the faintest clue what you're talking about. My role here is mainly to assign pushy buttons on my slidey box to the clever things you've spent hours mapping to Lightroom functions, then moan about it when I can't get them to work, like an annoying child.

I actually feel like a total bastard for just commenting on what doesn't work, given all the things that now work perfectly. Version 1 has pretty much delivered everything I wanted, with the exception of these issues, which seem to be a Mac "lost in translation" thing. So massive thanks for all the work you've put in on this - Midi2LR is shaping up to be pretty much perfect. Bravo!

If someone can explain to me in very, very simple terms how to do what Rory is requesting I'd happily give it a go (I feel like I should give something back given the amount of requests I put in) but it's probably better at this point if a grown-up/someone who knows what words like "compile" and "development branch" means takes over

Enjoy your travels dude. I'll buy you a steak dinner via the medium of PayPal once these things are sorted.
